name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set CI=false for this job
      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      # Clear npm cache
      - name: Clear npm cache
        run: npm cache clean -f

      # Install dependencies and update lock file
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKING_RECIPES_9BEA3 }}'
          channelId: live
          projectId: cooking-recipes-9bea3
